name: dist-s1
dependencies:
 - python>=3.10
 - pip
 - scikit-image
 - numpy
 - scipy
 - matplotlib
 - rasterio
 - astropy
 - gdal
 - pydantic
 - astropy
 - jupyterlab
 - tqdm
 - shapely
 - mpire
 - requests
 - backoff
 - asf_search
 - geopandas
 - pandas
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - pytest
 - pytest-cov
 - ruff